=== salesforce/grammaticus/src/test/resources/sample/labels.dtd
<!--
    Copyright (c) 2025, Salesforce, Inc.
    SPDX-License-Identifier: Apache-2

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!--
   SFDC labels DTD


-->
<!--======== parameter-entity to keep ATTLIST def consistent =============-->
<!-- simple boolean type -->
<!ENTITY % BOOLEAN    "(true|false)">
<!ENTITY % YN         "(y|n)">


<!--
An entity type. This could be either %entities; , %compoundNouns; or
number. If number is specified, that'll be resolved at runtime. -->
<!ENTITY % entityRef  "entity   CDATA">


<!--=================== Root element =====================================-->
<!ELEMENT iniFile ((section)*, (import)*)>


<!--=================== Standard section/param element ===================-->
<!ELEMENT section (param|image)*>
<!ATTLIST section
  name          NMTOKEN     #REQUIRED
  public        %BOOLEAN;        "false"
  all_languages %BOOLEAN;   #IMPLIED
  dnt           %BOOLEAN;   #IMPLIED
  >

<!--
alias attribute defines the element as a reference to the other element.
The type of the element on source and destination must be the same - that means
you cannot specify param alias to an image tag.
If this attribute is specified, any other attribute besides name, and
contents of the element will be ignored.
    ex: <param name="Test" alias="udd_Account.Entity"/>
-->
<!ENTITY % alias      "alias NMTOKEN">

<!--"y" for plural form, "n" for singular form -->
<!ENTITY % plural     "plural   %YN;">

<!--
case attribute is to determine:
    n   nominative (default)
    a   accusative
    g   genitive
    d   dative
    NOTE: this is required for German
    -->
<!ENTITY % case       "case     (n | a | g | d)">

<!--
article type
    n     no article (default)
    a|d   definite article "a" in English
    the|i indefinite article "the" in English
-->
<!ENTITY % article    "article (n|a|the|i|d)">

<!--
indicates this is for error text. if error="y" is given, and if
user has overwritten name of the entity, the result would be like
    Account(Hospital)

this display both only if user has different name in rename tab
    -->
<!ENTITY % error      "error   %YN;">

<!-- param element is generic values which contains plain text or compound-type
     data which is used in the labels file.
    -->
<!ELEMENT param (#PCDATA | entity | Entity | modifier)*>
<!ATTLIST param
  name          NMTOKEN     #REQUIRED
  %alias;                   #IMPLIED
  %entityRef;               #IMPLIED
  %case;                    #IMPLIED
  all_languages %BOOLEAN;   #IMPLIED
  dnt           %BOOLEAN;   #IMPLIED
  >

<!-- image element is to specify image (usually .gif) -->
<!ATTLIST image
  name          NMTOKEN     #REQUIRED
  %alias;                   #IMPLIED
  width         CDATA       #IMPLIED
  height        CDATA       #IMPLIED
  alt           CDATA       #IMPLIED
  align         CDATA       #IMPLIED
  label         CDATA       #IMPLIED
  >

<!--
entity element is replacement marker of %entities or %compoundNouns.
If there is no %entityRef specified, param element MUST have %entityRef

For any <%entities/> tag, there's no definition in this DTD.
    ATTLIST Account
    %case;                    #IMPLIED
    %article;                 #IMPLIED
    %error;                   #IMPLIED
    -->
<!ATTLIST entity
  %entityRef;               #IMPLIED
  %case;                    #IMPLIED
  %article;                 #IMPLIED
  %plural;                  "n"
  %error;                   #IMPLIED
  >

<!-- modifier element is replacement marker of %adjective. If there is no
     %entityRef specified, it is defaulting to:
     1) param element's %entityRef
     2) first entity (entity/Entity/%entities) appears in the same param
     -->
<!ATTLIST modifier
  type          CDATA       #REQUIRED
  %entityRef;               #IMPLIED
  %case;                    #IMPLIED
  >

<!-- import element specifies file to be included as part of the document -->
<!ELEMENT import EMPTY>
<!ATTLIST import
  file          CDATA       #REQUIRED
  >

<!--=================== Other elements ===================================-->
<!ELEMENT set (param*, import*, image*)>
<!ATTLIST set
  name          NMTOKEN     #REQUIRED
  >

=== salesforce/grammaticus/src/test/resources/sample/bg/sample.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
    Copyright (c) 2025, Salesforce, Inc.
    SPDX-License-Identifier: Apache-2

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!DOCTYPE iniFile
  SYSTEM "labels.dtd">
<iniFile>
    <!--
        "Exception" section is now in ex.xml.
    -->
    <section name="Combo" all_languages="yes" public="false">
        <param name="Title">Разгъващ се списък</param>
        <param name="select_default">Изберете от възможностите по-долу.</param>   <!-- aliased across labels; do not change -->
        <param name="select">Изберете {0} по-долу.</param>
        <!-- must sync with ComboBoxElement -->
        <param name="disp_1"><Subject_Activity/></param>
        <param name="disp_2" alias="Related_Lists.competitors_name"/>
        <param name="disp_3"><Primary/> <contact/></param>
    </section>
    <section name="Global_Entity" all_languages="yes" public="false">
        <param name="Access">Достъп</param>   <!-- aliased across labels; do not change -->
        <param name="ManagedHeader">(Управляван)</param>
        <param name="activity_history">История на дейността</param> <!--aliased across labels - do not change-->
        <param name="additional_info">Допълнителна информация</param> <!--aliased across labels - do not change-->
        <param name="alias">Псевдоним</param> <!--aliased across labels - do not change-->
        <param name="assigned_to"><Assigned_To_Activity/></param> <!--aliased across labels - do not change-->
        <param name="assistant">Асистент</param>
        <param name="assistant_name">Име на асистента</param>   <!-- aliased across labels; do not change -->
        <param name="assistant_phone">Телефон на асистента</param>   <!-- aliased across labels; do not change -->
        <param name="asst_phone">Тел. на асист.</param>   <!-- aliased across labels; do not change -->
        <param name="asst_phone_ext">Тел. код на асист.</param>   <!-- aliased across labels; do not change -->
        <param name="birthdate">Дата на раждане</param>   <!-- aliased across labels; do not change -->
        <param name="body">Текст</param>   <!-- aliased across labels; do not change -->
        <param name="company">Фирма</param> <!--aliased across labels - do not change-->
        <param name="created_by">Създател</param> <!--aliased across labels - do not change-->
        <param name="created_by_id">Идент. № на „Създадено от“</param>   <!-- aliased across labels; do not change -->
        <param name="created_by_alias">Създаден от псевдоним</param> <!--aliased across labels - do not change-->
        <param name="CurrencyIsoCode">ISO код на валутата</param>   <!-- aliased across labels; do not change -->
        <param name="custom_fields">Допълнителни полета</param> <!--aliased across labels - do not change-->
        <param name="default_status">Състояние по подразбиране</param>   <!-- aliased across labels; do not change -->
        <param name="detail">Подробност за {0}</param>   <!-- aliased across labels; do not change -->
        <param name="department">Отдел</param>   <!-- aliased across labels; do not change -->
        <param name="edit">Редактиране на {0}</param>   <!-- aliased across labels; do not change -->
        <param name="expected_revenue">Очакван приход</param>
        <param name="first_name">Собствено име</param> <!-- aliased across app - do not change -->
        <param name="last_name">Фамилия</param> <!-- aliased across app - do not change -->
        <param name="first_name_local">Собствено име (местно)</param>   <!-- aliased across labels; do not change -->
        <param name="last_name_local">Фамилия (местна)</param>   <!-- aliased across labels; do not change -->
        <param name="fiscal_quarter">Фискално тримесечие</param>   <!-- aliased across labels; do not change -->
        <param name="fiscal_year">Фискална година</param>   <!-- aliased across labels; do not change -->
        <param name="full_name">Пълно име</param> <!-- aliased across app - do not change -->
        <param name="group">Група</param> <!-- aliased across app - do not change -->
        <param name="group_name">Име на група</param>   <!-- aliased across labels; do not change -->
        <param name="queue_name">Име на опашката</param>   <!-- aliased across labels; do not change -->
        <param name="industry">Отрасъл</param>   <!-- aliased across labels; do not change -->
        <param name="last_modified_by">Последна промяна от</param> <!-- aliased across app - do not change -->
        <param name="last_modified_by_id">Последна промяна от идент. №</param>   <!-- aliased across labels; do not change -->
        <param name="last_modified_by_alias">Последна промяна от псевдоним</param><!-- aliased across app - do not change -->
        <param name="last_update_by" alias="Global_Entity.last_modified_by"/>
        <param name="master_record_id">Идент. № на главния запис</param>
        <param name="mobile">Мобилен</param>   <!-- aliased across labels; do not change -->
        <param name="mobile_phone">Мобилен телефон</param> <!-- aliased across app - do not change -->
        <param name="mobile_phone_ext">Код на мобилен телефон</param>   <!-- aliased across labels; do not change -->
        <param name="new_sharing">Ново споделяне</param>   <!-- aliased across labels; do not change -->
        <param name="assigned_alias">Присвоен псевдоним</param>   <!-- aliased across labels; do not change -->
        <param name="available_list">Наличен списък</param>   <!-- aliased across labels; do not change -->
        <param name="company_name">Име на фирмата</param> <!-- aliased across app - do not change -->
        <param name="activities">Дейности</param>   <!-- aliased across labels; do not change -->
        <param name="no_attachments">няма прикачени файлове</param>   <!-- aliased across labels; do not change -->
        <param name="no_documents"><no/> <document plural="y"/></param>
        <param name="address_info">Адресна информация</param>   <!-- aliased across labels; do not change -->
        <param name="declined">Отхвърлена</param>   <!-- aliased across labels; do not change -->
        <param name="default">По подразбиране</param>  <!-- aliased across labels; do not change -->
        <param name="default_priority">Приоритет по подразбиране</param> <!-- aliased across app - do not change -->
        <param name="create_new_view">Създаване на нов изглед</param>   <!-- aliased across labels; do not change -->
        <param name="custom_info">Допълнителна информация</param> <!-- aliased across app - do not change -->
        <param name="duplicate_status">Дублиране на състоянието</param> <!-- aliased across app - do not change -->
        <param name="email_address">Имейл адрес</param> <!-- aliased across app - do not change -->
        <param name="email_name">Име на имейл</param>   <!-- aliased across labels; do not change -->
        <param name="email_template">Образец за имейл</param>   <!-- aliased across labels; do not change -->
        <param name="email">Имейл:</param>   <!-- aliased across labels; do not change -->
        <param name="enterprise_integration_links">Допълнителни връзки</param>   <!-- aliased across labels; do not change -->
        <param name="file_size">Размер на файл</param> &gt;<!-- aliased across app - do not change -->
        <param name="history" alias="Related_Lists.history_title"/>
        <param name="history_event_unavailable">Няма налични данни</param>
        <param name="history_event_checked">Маркирано поле {0}</param>
        <param name="history_event_unchecked">Немаркирано поле {0}</param>
        <param name="how_do_i_specify_info">Как да посоча коя информация да се въвежда?</param>   <!-- aliased across labels; do not change -->
        <param name="internal_source">Вътрешен източник</param>   <!-- aliased across labels; do not change -->
        <param name="interval">Интервал:</param>   <!-- aliased across labels; do not change -->
        <param name="salutation">Привет</param>   <!-- aliased across labels; do not change -->
        <param name="select_new_owner">Избор на нов собственик</param>
        <param name="select_a_view">Изберете изглед от падащия списък, за да видите списък със свързани резултати.</param>   <!-- aliased across labels; do not change -->
        <param name="select_a_folder">Изберете папка от падащия списък, за да видите списък със свързани резултати.</param>
        <param name="select_the_file">Изберете файла</param> &gt;<!-- aliased across app - do not change -->
        <param name="select_the_fields">Изберете полетата, които да бъдат включени:</param>   <!-- aliased across labels; do not change -->
        <param name="signature">Подпис</param>   <!-- aliased across labels; do not change -->
        <param name="size" alias="Related_Lists.documents_size"/>
        <param name="subject">Тема</param> <!-- aliased across app - do not change -->
        <param name="system_info">Системна информация</param>   <!-- aliased across labels; do not change -->
        <param name="website">Уебсайт</param>   <!-- aliased across labels; do not change -->
        <param name="owner" alias="Global.owner"/>
        <param name="owner_alias">Псевдоним на собственика</param>   <!-- aliased across labels; do not change -->
        <param name="owner_first_name">Собствено име на собственика</param>   <!-- aliased across labels; do not change -->
