=== salesforce/grammaticus/src/test/resources/sample/uk/names.dtd
<!--
   Dictionary DTD for UKRAINIAN

   see i18n.grammar.LanguageDeclension for more information
-->
<!-- simple boolean type -->
<!ENTITY % BOOLEAN    "(true|false)">
<!ENTITY % YN         "(y|n)">

<!--=================== dictionary elements ==============================-->

<!-- "entity" if this is standard object(tab) name -->
<!ENTITY % noun.type  "type     (entity | field | other)">

<!-- "m" for Masculine, "f" for Feminine, "n" for Neuter,
     "e" for Euter (Swedish) and "c" for Common (Dutch) -->
<!ENTITY % gender     "gender   (n | f | c | e | m)">

<!--
Specifying the type of first letter(or soft sound) of noun
    c:  consonant    (default)
    v:  starts with vowel.
    s:  S(consonant) or Z (for Italian)
    -->
<!ENTITY % starts     "startsWith  (c | v)">

<!--"y" for plural form, "n" for singular form -->
<!ENTITY % plural     "plural   %YN;">

<!--
case attribute is to determine:  (nominative is default)
    n    Nominative case
    a    Accusative case
    g    Genitive case
    d    Dative case
    in    Instrumental case
    l    Locative case
    v    Vocative case
    -->
<!ENTITY % case       "case     (n | a | g | d | in | l | v)">

<!--
standard field
		default is "y" (yes)
	y	is standard field (yes)
	n	is not a standard field (no)
	-->
<!ENTITY % standardField "standardField %YN;">
<!--=================== Root element =====================================-->
<!ELEMENT names ((noun)+, (adjective)*, (article)*, (import)*)>

<!--
noun element is used to specify translation of nouns
    name:   specify either  %entity; or %compoundNouns;
    alias:   The alias used in label files to refer to the object in the plural
    entity:  The object type associated with this label
    type:   "entity" if this is for standard object, where all form are required
            "field" if this requires both singular/plural form,
              other forms are not required, but can be specified and renamed
    gender:  The gender of the noun as defined here
    -->
<!ELEMENT noun (value)+>
<!ATTLIST noun
  name          ID          #REQUIRED
  alias		CDATA       #IMPLIED
  entity	CDATA	    #IMPLIED
  access        CDATA       #IMPLIED
  %noun.type;               #IMPLIED
  %gender;                   #REQUIRED
  %starts;                  "c"
  %standardField;	    #IMPLIED
  >

<!--
adjective element is used to specify translation of adjectives
    position: whether this adjective comes before or after the noun, usually.
    name:   specify name of this adjective
    -->
<!ELEMENT adjective (value)+>
<!ATTLIST adjective
  name          ID          #REQUIRED
  position      (b|a)       #IMPLIED
  >

<!--
article element is used to specify translation of articles and other determiners
    name:   specify name of this adjective
    -->
<!ELEMENT article (value)+>
<!ATTLIST article
  name          ID          #REQUIRED
  type          (n|a|the|i|d)     #REQUIRED
  >

<!--
import element specifies file to be included as part of the document
    -->
<!ELEMENT import EMPTY>
<!ATTLIST import
  file          CDATA       #REQUIRED
  >

<!--
value element is shared by both noun/adjective.
    -->
<!ELEMENT value (#PCDATA)>
<!ATTLIST value

  %plural;                   #REQUIRED
  %gender;                  "n"
  %case;                    "n"
  >

=== salesforce/grammaticus/src/test/resources/sample/uk/names.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2025, Salesforce, Inc.
    SPDX-License-Identifier: Apache-2

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!DOCTYPE names SYSTEM "names.dtd">
<names>
<!--==========================================================================
 <noun> Syntax:
    Required attributes:
       name:  name of this noun. use element like: <Activity/>
       entity: specify which entity this noun belongs to. Must be one of the
               existing entity.

    Optional attributes:
       alias: alias to this noun in plural form like: <Activitys/>
       type:  specify type of noun. mainly used by setup UI. If none specified,
              the noun is considered like proper noun. just singular value is
              required.
        "entity": this noun requires full set of values - combination of
                  number, article and cases. It is not necessary that this
                  type of noun should be a real entity (like Activity).
        "field" : this is field name which requires only singular
                  and plural form. no article or cases

       gender: (n)eutor | (f)eminine | (m)asculine | (e)utor - default is n
       startsWith: (c)onsonant | (v)owel | (s)consonant or Z - default is c

    Note: if no optional attribute is given, it will be:
        gender="n" startsWith="c"

 <values> Syntax:
    Optional attributes:
       case:   (n)moninative | (a)ccusative | (g)enitive | (d)ative
           or  (o)bjective | (s)ubjective
       plural: (y)es | (n)o                                       - default is n
       article: (n)one | (a) | (the) | (d)efinite | (i)ndefinite  - default is n

    Note: if no attributes specified, the default value is equivalent to:
        <value case="n" plural="n" article="n"></value>
===========================================================================-->

    <!--======================================================================
     Standard Object
        for English, article forms like following are automatically
        resolved by the label generator. SO it is not necessary to specify here.
        <value plural="n" article="a">A partner</value>
        <value plural="n" article="the">The partner</value>
        <value plural="y" article="the">The partners</value>
    =======================================================================-->

    <noun name="Account" entity="Account" type="entity" alias="Accounts"  gender="m"  startsWith="c">
        <value plural="n">Обліковий запис</value>
    	<value plural="y">Облікові записи</value>
   		<value plural="n" case="a">Обліковий запис</value>
        <value plural="y" case="a">Облікові записи</value>
        <value plural="n" case="d">Обліковому запису</value>
        <value plural="y" case="d">Обліковим записам</value>
        <value plural="n" case="g">Облікового запису</value>
        <value plural="y" case="g">Облікових записів</value>
        <value plural="n" case="in">Обліковим записом</value>
        <value plural="y" case="in">Обліковими записами</value>
        <value plural="n" case="l">Обліковому запису</value>
        <value plural="y" case="l">Облікових записах</value>
    </noun>

   <noun name="Activity" entity="Activity" type="entity" alias="Activities" gender="f" startsWith="c">
        <value plural="n">Операція</value>
    	<value plural="y">Операції</value>
   		<value plural="n" case="a">Операцію</value>
        <value plural="y" case="a">Операції</value>
        <value plural="n" case="d">Операції</value>
        <value plural="y" case="d">Операціям</value>
        <value plural="n" case="g">Операції</value>
        <value plural="y" case="g">Операцій</value>
        <value plural="n" case="in">Операцією</value>
        <value plural="y" case="in">Операціями</value>
        <value plural="n" case="l">Операції</value>
        <value plural="y" case="l">Операціях</value>
    </noun>


    	<noun name="Campaign" entity="Campaign" type="entity" alias="Campaigns" gender="f" startsWith="c">
        <value plural="n">Кампанія</value>
  		<value plural="y">Кампанії</value>
   		<value plural="n" case="a">Кампанію</value>
        <value plural="y" case="a">Кампанії</value>
        <value plural="n" case="d">Кампанії</value>
        <value plural="y" case="d">Кампаніям</value>
        <value plural="n" case="g">Кампанії</value>
        <value plural="y" case="g">Кампаній</value>
        <value plural="n" case="in">Кампанією</value>
        <value plural="y" case="in">Кампаніями</value>
        <value plural="n" case="l">Кампанії</value>
        <value plural="y" case="l">Кампаніях</value>
    </noun>


	<!-- Content -->

    	<!-- // Content -->


        <noun name="Document" entity="Document" type="entity" alias="Documents" gender="m" startsWith="c">
        <value plural="n">Документ</value>
   		<value plural="y">Документи</value>
		<value plural="n" case="a">Документ</value>
        <value plural="y" case="a">Документи</value>
        <value plural="n" case="d">Документу</value>
        <value plural="y" case="d">Документам</value>
        <value plural="n" case="g">Документу</value>
        <value plural="y" case="g">Документів</value>
        <value plural="n" case="in">Документом</value>
        <value plural="y" case="in">Документами</value>
        <value plural="n" case="l">Документі</value>
        <value plural="y" case="l">Документах</value>
    </noun>


    <noun name="Event" entity="Event" type="entity" alias="Events" gender="f" startsWith="c">
        <value plural="n">Подія</value>
		<value plural="y">Події</value>
   		<value plural="n" case="a">Подію</value>
        <value plural="y" case="a">Подіх</value>
        <value plural="n" case="d">Події</value>
        <value plural="y" case="d">Подіям</value>
        <value plural="n" case="g">Події</value>
        <value plural="y" case="g">Подій</value>
        <value plural="n" case="in">Подією</value>
        <value plural="y" case="in">Подіями</value>
        <value plural="n" case="l">Події</value>
        <value plural="y" case="l">Подіях</value>
    </noun>




    <noun name="Lead" entity="Lead" type="entity" alias="Leads" gender="m" startsWith="c">
        <value plural="n">Інтерес</value>
		<value plural="y">Інтереси</value>
   		<value plural="n" case="a">Інтерес</value>
        <value plural="y" case="a">Інтереси</value>
        <value plural="n" case="d">Інтересу</value>
        <value plural="y" case="d">Інтересам</value>
        <value plural="n" case="g">Інтересу</value>
        <value plural="y" case="g">Інтересів</value>
        <value plural="n" case="in">Інтересом</value>
        <value plural="y" case="in">Інтересами</value>
        <value plural="n" case="l">Інтересі</value>
        <value plural="y" case="l">Інтересах</value>
    </noun>












    <noun name="Opportunity" entity="Opportunity" type="entity" alias="Opportunities" gender="f" startsWith="c">
        <value plural="n">Можливість</value>
		<value plural="y">Можливості</value>
   		<value plural="n" case="a">Можливість</value>
        <value plural="y" case="a">Можливості</value>
        <value plural="n" case="d">Можливості</value>
        <value plural="y" case="d">Можливостям</value>
        <value plural="n" case="g">Можливості</value>
        <value plural="y" case="g">Можливостей</value>
       <value plural="n" case="in">Можливістю</value>
        <value plural="y" case="in">Можливостями</value>
       <value plural="n" case="l">Можливості</value>
        <value plural="y" case="l">Можливостях</value>
    </noun>

		          <noun name="Pricebook" entity="Pricebook" type="entity" alias="Pricebooks" gender="m" startsWith="c">
        <value plural="n">Прейскурант</value>
		<value plural="y">Прейскуранти</value>
   		<value plural="n" case="a">Прейскурант</value>
        <value plural="y" case="a">Прейскуранти</value>
        <value plural="n" case="d">Прейскуранту</value>
        <value plural="y" case="d">Прейскурантам</value>
        <value plural="n" case="g">Прейскуранта</value>
        <value plural="y" case="g">Прейскурантів</value>
        <value plural="n" case="in">Прейскурантом</value>
        <value plural="y" case="in">Прейскурантами</value>
        <value plural="n" case="l">Прейскуранті</value>
        <value plural="y" case="l">Прейскурантах</value>
    </noun>

    <noun name="Question" entity="Question" type="entity" alias="Questions" gender="n" startsWith="c">
        <value plural="n">Питання</value>
        <value plural="y">Питання</value>
        <value plural="n" case="a">Питання</value>
        <value plural="y" case="a">Питання</value>
        <value plural="n" case="d">Питанню</value>
        <value plural="y" case="d">Питанням</value>
        <value plural="n" case="g">Питання</value>
        <value plural="y" case="g">Питань</value>
        <value plural="n" case="in">Питанням</value>
        <value plural="y" case="in">Питаннями</value>
        <value plural="n" case="l">Питанні</value>
        <value plural="y" case="l">Питаннях</value>
    </noun>




<noun name="Quote" entity="Quote" type="entity" alias="Quotes" gender="f" startsWith="c">
 <value plural="n">Пропозиція</value>
       <value plural="y">Пропозиції</value>
       <value plural="n" case="a">Припозицію</value>
       <value plural="y" case="a">Пропозициї</value>
        <value plural="n" case="g">Пропозиції</value>
        <value plural="y" case="g">Пропозицій</value>
